@id=00000000-0000-0000-0000-000000000000
PUT http://localhost:5190/users/{{id}}
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Smith",
    "groups": [
        "Apartment A",
        "Apartment B"
    ]
}