// <auto-generated />
using System;
using HomieCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomieCore.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomieCore.Data.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupDescription = "Wasted Potential",
                            GroupName = "Night's Watch",
                            LastModifiedTime = new DateTime(2023, 6, 22, 22, 59, 4, 245, DateTimeKind.Utc).AddTicks(7133)
                        },
                        new
                        {
                            Id = 2,
                            GroupDescription = "PC Port Is Going To Take So Long",
                            GroupName = "Rosaria Nobels",
                            LastModifiedTime = new DateTime(2023, 6, 22, 22, 59, 4, 245, DateTimeKind.Utc).AddTicks(7134)
                        });
                });

            modelBuilder.Entity("HomieCore.Data.GroupTask", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("integer");

                    b.Property<int>("TasksId")
                        .HasColumnType("integer");

                    b.HasKey("GroupsId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("GroupTask");

                    b.HasData(
                        new
                        {
                            GroupsId = 1,
                            TasksId = 1
                        },
                        new
                        {
                            GroupsId = 2,
                            TasksId = 2
                        });
                });

            modelBuilder.Entity("HomieCore.Data.GroupUser", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("GroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GroupUser");

                    b.HasData(
                        new
                        {
                            GroupsId = 1,
                            UsersId = 1
                        },
                        new
                        {
                            GroupsId = 1,
                            UsersId = 2
                        },
                        new
                        {
                            GroupsId = 2,
                            UsersId = 1
                        },
                        new
                        {
                            GroupsId = 2,
                            UsersId = 2
                        });
                });

            modelBuilder.Entity("HomieCore.Data.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompleteByDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TaskCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CreatedUserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedUserId = 2,
                            CompleteByDate = new DateTime(2023, 6, 22, 22, 59, 4, 245, DateTimeKind.Utc).AddTicks(7142),
                            CreatedUserId = 1,
                            LastModifiedDateTime = new DateTime(2023, 6, 22, 22, 59, 4, 245, DateTimeKind.Utc).AddTicks(7143),
                            TaskCreatedDate = new DateTime(2023, 6, 22, 22, 59, 4, 245, DateTimeKind.Utc).AddTicks(7142),
                            TaskDescription = "You know Nuthin Jon Snow",
                            TaskName = "Free The North"
                        },
                        new
                        {
                            Id = 2,
                            AssignedUserId = 1,
                            CompleteByDate = new DateTime(2023, 6, 22, 22, 59, 4, 245, DateTimeKind.Utc).AddTicks(7144),
                            CreatedUserId = 2,
                            LastModifiedDateTime = new DateTime(2023, 6, 22, 22, 59, 4, 245, DateTimeKind.Utc).AddTicks(7145),
                            TaskCreatedDate = new DateTime(2023, 6, 22, 22, 59, 4, 245, DateTimeKind.Utc).AddTicks(7145),
                            TaskDescription = "Will That Really Solve Anything?",
                            TaskName = "Get Revenge"
                        });
                });

            modelBuilder.Entity("HomieCore.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Jon",
                            LastModifiedDateTime = new DateTime(2023, 6, 22, 22, 59, 4, 245, DateTimeKind.Utc).AddTicks(7041),
                            LastName = "Snow"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Clive",
                            LastModifiedDateTime = new DateTime(2023, 6, 22, 22, 59, 4, 245, DateTimeKind.Utc).AddTicks(7043),
                            LastName = "Rosfield"
                        });
                });

            modelBuilder.Entity("HomieCore.Data.GroupTask", b =>
                {
                    b.HasOne("HomieCore.Data.Group", "Group")
                        .WithMany("GroupTasks")
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomieCore.Data.Task", "Task")
                        .WithMany("GroupTasks")
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("HomieCore.Data.GroupUser", b =>
                {
                    b.HasOne("HomieCore.Data.Group", "Group")
                        .WithMany("GroupUsers")
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomieCore.Data.User", "User")
                        .WithMany("GroupUsers")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomieCore.Data.Task", b =>
                {
                    b.HasOne("HomieCore.Data.User", "AssignedUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("HomieCore.Data.User", "CreatedUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedUserId");

                    b.Navigation("AssignedUser");

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("HomieCore.Data.Group", b =>
                {
                    b.Navigation("GroupTasks");

                    b.Navigation("GroupUsers");
                });

            modelBuilder.Entity("HomieCore.Data.Task", b =>
                {
                    b.Navigation("GroupTasks");
                });

            modelBuilder.Entity("HomieCore.Data.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedTasks");

                    b.Navigation("GroupUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
